apiVersion: cordum.io/v1alpha1
kind: Pack

metadata:
  id: mcp-client
  version: 0.1.0
  title: MCP Client
  description: Call external MCP servers from Cordum jobs with policy gating.

compatibility:
  protocolVersion: 1
  minCoreVersion: 0.1.0

topics:
  - name: job.mcp-client.call
    requires: ["network:egress"]
    riskTags: ["write"]
    capability: mcp.client.call

resources:
  schemas:
    - id: mcp-client/McpCallInput
      path: schemas/McpCallInput.json
    - id: mcp-client/McpCallResult
      path: schemas/McpCallResult.json
  workflows:
    - id: mcp-client.call
      path: workflows/mcp_client_call.yaml

overlays:
  config:
    - name: pools
      scope: system
      key: pools
      strategy: json_merge_patch
      path: overlays/pools.patch.yaml
    - name: timeouts
      scope: system
      key: timeouts
      strategy: json_merge_patch
      path: overlays/timeouts.patch.yaml
  policy:
    - name: safety
      strategy: bundle_fragment
      path: overlays/policy.fragment.yaml

tests:
  policySimulations:
    - name: allow_read_calls
      request:
        tenantId: default
        topic: job.mcp-client.call
        riskTags: ["read"]
      expectDecision: ALLOW
    - name: write_requires_approval
      request:
        tenantId: default
        topic: job.mcp-client.call
        riskTags: ["write"]
      expectDecision: REQUIRE_APPROVAL
    - name: secrets_require_approval
      request:
        tenantId: default
        topic: job.mcp-client.call
        riskTags: ["secrets"]
      expectDecision: REQUIRE_APPROVAL
